name: Bump Version
on:
  workflow_dispatch:
    inputs:
      version:
jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Bump Version
        run: |
          sed -i s/QVersionNumber::fromString\(.*\)/QVersionNumber::fromString\(\"${{ github.event.inputs.version }}\"\)/ src/window.cpp
      - name: Create PR
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          token: ${{ secrets.MINIKUBE_BOT_PAT }}
          commit-message: Bump version
          committer: minikube-bot <minikube-bot@google.com>
          author: minikube-bot <minikube-bot@google.com>
          branch: bump_version
          push-to-fork: minikube-bot/minikube-gui
          base: main
          delete-branch: true
          title: 'Bump version'
