name: Build Linux
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: jurplel/install-qt-action@37e649dae477dba3481cbec4788e5b3ca9d6e170
        with:
          cache: true
      - name: build & package
        run: |
          make build-linux
          make package-linux
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: minikube-gui-linux
          path: ./minikube-gui-linux.tar.gz
