name: Tag
on:
  workflow_dispatch:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Get Version
        run: |
          export VERSION=$(sed -n -e 's/.*QVersionNumber::fromString(\"\(.*\)\");/\1/p' src/window.cpp)
          echo "version=$VERSION" >> $GITHUB_ENV
      - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ env.version }}',
              sha: context.sha
            })
